# Generated by Django 3.2 on 2024-08-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yauser',
            name='confirmation_code',
        ),
    ]
