NAME_FIELD_LENGTH = 256
SLUG_FIELD_LENGTH = 50
EMAIL_FIELD_LENGTH = 254
USERNAME_FIELD_LENGTH = 150
ROLE_FIELD_LENGTH = 9

ROLE_ADMIN = 'admin'
ROLE_MODERATOR = 'moderator'
ROLE_USER = 'user'

REVIEW_MIN_RATE = 0
REVIEW_MAX_RATE = 100
